Plat200 distributed resque worker
YourMechanic/distributed_resque_worker pull request #1
Opened 2021-04-09 12:43 UTC by TruptiHosmani

2021-04-09 14:45 UTC, sachinsaxena1996 commented on .ruby-version
> +2.3.8
@TruptiHosmani please correct the ruby version

2021-04-09 14:45 UTC, sachinsaxena1996 commented on lib/distributed_resque_worker.rb
> +  class Notify < ActionMailer::Base
@TruptiHosmani why not create a new file for this class.

2021-04-09 14:45 UTC, sachinsaxena1996 commented on .travis.yml
> +---
@TruptiHosmani this file is not required if you are using circleci for CI

2021-04-09 14:45 UTC, sachinsaxena1996 commented on spec/distributed_resque_worker_spec.rb
> +    puts info
@TruptiHosmani can we remove this puts

2021-04-09 14:45 UTC, sachinsaxena1996 commented on spec/distributed_resque_worker_spec.rb
> +
@TruptiHosmani can you please add more test cases which would enable the reader of the rspec to understand its behaviour.

2021-04-12 17:02 UTC, TruptiHosmani commented on spec/distributed_resque_worker_spec.rb
> +    puts info
ok

2021-04-12 17:02 UTC, TruptiHosmani commented on .travis.yml
> +---
ok

2021-04-12 17:13 UTC, TruptiHosmani commented on .ruby-version
> +2.3.8
Casa uses ruby 2.3.8

2021-04-14 04:37 UTC, siddyg requested changes

2021-04-14 04:37 UTC, siddyg commented on lib/distributed_resque_worker/aws_helper.rb
> +module AwsHelper
can we make aws configuration as a required configuration for this gem? 
Also make any YM related info (such as default bucket) in this module into a gem configuration

2021-04-14 04:37 UTC, siddyg commented on distributed_resque_worker.gemspec
> +  spec.homepage      = 'https://github.com/YourMechanic/ym-resque-worker'
pls fix instances of ym-resque-worker here

2021-04-14 04:37 UTC, siddyg commented on lib/distributed_resque_worker.rb
> +  class Error < StandardError; end
dont see a usage for this error class

2021-04-14 04:37 UTC, siddyg commented on Rakefile
> +  ActiveSupport.on_load(:before_initialize) { config.eager_load = false }
this change is a little concerning:
1. does this mean we would be disabling eager_load in production?
2. From what I read, dont we actually need eager_load to be true in this rake task since eager loading is false in all rake tasks by default?
https://stackoverflow.com/questions/4300240/rails-3-rake-task-cant-find-model-in-production

2021-04-14 04:37 UTC, siddyg commented on lib/distributed_resque_worker.rb
> +      @queue = "#{queue_name}_#{Time.now.to_i}_#{Random.rand(1_000_000)}"
Can we use 1000000 instead of 1_000_000? I know rubocop complains about this - can we make that rubocop an exception similar to how @sachinsaxena1996 did on factory?

2021-04-14 04:37 UTC, siddyg commented on spec/distributed_resque_worker_spec.rb
> +
@TruptiHosmani can you pls add the test cases we discussed in the call

2021-04-14 04:37 UTC, siddyg commented on lib/distributed_resque_worker.rb
> +          type: 'master', work_name: work_name, method: method, opts: opts
can we change master/slave to primary/secondary or post_processor/processor ?
Related to https://cdm.link/2020/06/lets-dump-master-slave-terms/

2021-04-14 04:37 UTC, siddyg commented on lib/distributed_resque_worker.rb
> +        worker.call(chunk, filename, opts)
is this making an implicit assumption on the definition of the method defined by the caller?
Can we not just do `worker_class.constantize.send(method, *args) `similar to https://github.com/YourMechanic/YourMechanicData/blob/master/ETL/analytics/app/utils/manual_worker_util.rb#L20

2021-04-14 04:37 UTC, siddyg commented on lib/distributed_resque_worker.rb
> +    def chunk_work_and_enqueue(work_list, method, root, opts)
I was thinking about this more today and is it possible to enhance this:
1. Should we support this without work_list too i.e. think of the P&Q downloads that happen via OpsHelper module. I am thinking of how something like OpsHelper or CasaAdmin::CaseListController#get_file OR PartCatalogUpdater use this gem. Do you have ideas around that?

2. Should we have a the caller of the gem pass in a post processing method so its upto the caller what it wants to do with the S3 link of the final csv file i.e. it may want to email or slack or have a completely different post processing method? This would take the onus out of this gem and it doesnt need requestor info and even do email etc.
Let me know thoughts, happy to discuss further.

2021-04-14 09:48 UTC, TruptiHosmani commented on lib/distributed_resque_worker.rb
> +          type: 'master', work_name: work_name, method: method, opts: opts
ok

2021-04-27 00:58 UTC, siddyg requested changes

2021-04-27 00:58 UTC, siddyg commented on README.md
> +Add th following in routes.rb
typo

2021-04-27 00:58 UTC, siddyg commented on log/dev_resque.log
> +# Logfile created on 2021-04-26 12:55:36 +0530 by logger.rb/56438
log folder should be git ignored

2021-04-27 00:58 UTC, siddyg commented on lib/distributed_resque_worker.rb
> +    CHUNK_SIZE = 1000
thought we discussed chunk size of 100 no?

2021-04-27 00:58 UTC, siddyg commented on lib/distributed_resque_worker.rb
> +  class Error < StandardError; end
still dont see a usage for this

2021-04-27 00:58 UTC, siddyg commented on distributed_resque_worker.gemspec
> +  spec.add_dependency 'activerecord'
why do we need activerecord and activesupport for this gem?

2021-04-27 00:58 UTC, siddyg commented on README.md
> +staging: redis1.se.github.com:6379
this should be REDIS_URL env variable no? What is this github URL?

2021-04-27 00:58 UTC, siddyg commented on Rakefile
> +def run_worker(queue, count = 1)
I dont see anyone calling these resque rake tasks - why do we need these here?
These should be defined in CASA or the user of this gem correct?

2021-04-27 00:58 UTC, siddyg commented on config.ru
> +  '/' => Resque::Server.new
This should only be in the user of this gem no?

2021-04-27 00:58 UTC, siddyg commented on lib/distributed_resque_worker.rb
> +        "#{bucket}.yourmechanic.com"
we should let the user define the whole bucket name and not just the prefix of the bucket name i.e. remove any yourmechanic.com dependencies from this gem

2021-04-27 00:58 UTC, siddyg commented on lib/distributed_resque_worker.rb
> +    WORKERS = 4
this constant doesn't seem to be used

2021-04-27 00:58 UTC, siddyg commented on lib/distributed_resque_worker.rb
> +      resque_redis.redis.setex(ResqueWorker.resque_worker_redis_key(@queue), 86400, total_jobs)
why do we need to set this expiry of 24 hours?

2021-04-27 00:58 UTC, siddyg commented on lib/distributed_resque_worker.rb
> +      def clean_up(queue_name, root)
dont see this being called anywhere, shouldnt this be called before `worker.send` in `upload_final_file_to_s3_and_send` ?

2021-04-27 00:58 UTC, siddyg commented on lib/distributed_resque_worker.rb
> +        FileUtils.mkdir_p("#{root}/tmp/#{work_name}")
do we need to do this again if this is already done in initialize?

2021-04-27 00:58 UTC, siddyg commented on lib/distributed_resque_worker.rb
> +      def perform(args)
all methods except `perform` should be private no?

2021-04-27 07:02 UTC, TruptiHosmani commented on README.md
> +Add th following in routes.rb
ok

2021-04-27 07:02 UTC, TruptiHosmani commented on log/dev_resque.log
> +# Logfile created on 2021-04-26 12:55:36 +0530 by logger.rb/56438
ok

2021-04-27 07:05 UTC, TruptiHosmani commented on config.ru
> +  '/' => Resque::Server.new
I need this when I tested the gem. Should I remove this?

2021-04-27 07:05 UTC, TruptiHosmani commented on lib/distributed_resque_worker.rb
> +        "#{bucket}.yourmechanic.com"
ok

2021-04-27 07:06 UTC, TruptiHosmani commented on lib/distributed_resque_worker.rb
> +      resque_redis.redis.setex(ResqueWorker.resque_worker_redis_key(@queue), 86400, total_jobs)
how much should I put the expiry as? 12 hrs, 6 hrs?

2021-04-27 07:08 UTC, siddyg commented on lib/distributed_resque_worker.rb
> +      resque_redis.redis.setex(ResqueWorker.resque_worker_redis_key(@queue), 86400, total_jobs)
@TruptiHosmani why do you need expiry at all?

2021-04-27 07:09 UTC, TruptiHosmani commented on lib/distributed_resque_worker.rb
> +      def clean_up(queue_name, root)
after the upload_final_file_to_s3_and_send in post_processing function

2021-04-27 08:29 UTC, TruptiHosmani commented on lib/distributed_resque_worker.rb
> +      def perform(args)
yes most of them I can make them private

2021-04-27 08:29 UTC, TruptiHosmani commented on lib/distributed_resque_worker.rb
> +        FileUtils.mkdir_p("#{root}/tmp/#{work_name}")
true

2021-04-27 08:32 UTC, TruptiHosmani commented on lib/distributed_resque_worker.rb
> +      resque_redis.redis.setex(ResqueWorker.resque_worker_redis_key(@queue), 86400, total_jobs)
ok, will remove expiry

2021-04-27 08:35 UTC, TruptiHosmani commented on lib/distributed_resque_worker.rb
> +    WORKERS = 4
removed unused

2021-04-27 08:35 UTC, TruptiHosmani commented on lib/distributed_resque_worker.rb
> +    CHUNK_SIZE = 1000
yes updated this

2021-04-27 08:49 UTC, TruptiHosmani commented on README.md
> +staging: redis1.se.github.com:6379
yes

2021-04-27 08:50 UTC, TruptiHosmani commented on Rakefile
> +def run_worker(queue, count = 1)
yes I agree

2021-04-27 08:50 UTC, TruptiHosmani commented on lib/distributed_resque_worker.rb
> +        "#{bucket}.yourmechanic.com"
ok

2021-04-30 17:28 UTC, siddyg approved these changes
@TruptiHosmani functionality looks good to go, some minor comments but other than that good to merge

2021-04-30 17:28 UTC, siddyg commented on lib/distributed_resque_worker.rb
> +  class Error < StandardError; end
@TruptiHosmani

2021-04-30 17:28 UTC, siddyg commented on README.md
> +fi: localhost:6379
what is "fi"?

2021-04-30 17:28 UTC, siddyg commented on Rakefile
> +def run_worker(queue, count = 1)
do we need this method here?

2021-04-30 17:28 UTC, siddyg commented on Rakefile
> +task 'resque:setup' do
do we need this rake task here?

2021-04-30 17:28 UTC, siddyg commented on lib/distributed_resque_worker.rb
> +      def resque_redis
any reason these 3 methods are not private?

2021-04-30 17:28 UTC, siddyg commented on README.md
> +    def self.method_name(work_chunk, output_filepath, opts = {})
is this correct? shouldnt this be `method_name_chunk` and `method_name_post` ?

2021-04-30 17:28 UTC, siddyg commented on .gitignore
> -/tmp/
why isnt tmp folder in your gitignore?Would request to review this file and compare to CASA to make sure this is correct
```
/tmp/*
/log/*
```

2021-04-30 17:28 UTC, siddyg commented on lib/distributed_resque_worker.rb
> +        system(`cat #{final_tmp_file}`)
why do we need to cat the final file?

2021-04-30 18:04 UTC, TruptiHosmani commented on lib/distributed_resque_worker.rb
> +        system(`cat #{final_tmp_file}`)
removed

2021-04-30 18:35 UTC, TruptiHosmani commented on Rakefile
> +def run_worker(queue, count = 1)
removed it

2021-04-30 18:38 UTC, TruptiHosmani commented on Rakefile
> +task 'resque:setup' do
yes we need this

2021-04-30 18:41 UTC, TruptiHosmani commented on .gitignore
> -/tmp/
ok

2021-04-30 18:43 UTC, TruptiHosmani commented on README.md
> +fi: localhost:6379
removed it,

2021-05-12 07:48 UTC, merged